### FULL CREDIT FOR automating updating submodules: 
# https://stackoverflow.com/a/67059629

### Info on running workflow at fixed times:
# https://jasonet.co/posts/scheduled-actions/

### Token format to use
# https://github.com/actions/checkout/issues/298#issuecomment-820748989


# This is a basic workflow to help you get started with Actions

name: "Automatic Submodules Update"

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # https://github.com/actions/checkout/issues/298#issuecomment-820748989
          token: ${{ secrets.MY_TOKEN || github.token }}
          submodules: true

      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
        
      - name: Commit updates from submodules
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Auto updated submodule references" && git push || echo "No changes to commit"


